version: "3"

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - type: bind
        source: /mnt/PlexMedia
        target: ./media
      - ./config:/config
      - ./transcode:/transcode
    restart: unless-stopped
