version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.entrypoints=http"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.local.mmckinneyjr.com`)"
      - "traefik.http.middlewares.homeassistant-https-redirect.redirectscheme.scheme=https"
      
      - "traefik.http.routers.homeassistant.middlewares=homeassistant-https-redirect"
      - "traefik.http.routers.homeassistant-secure.entrypoints=https"
      - "traefik.http.routers.homeassistant-secure.rule=Host(`homeassistant.local.mmckinneyjr.com`)"
      - "traefik.http.routers.homeassistant-secure.tls=true"
      - "traefik.http.routers.homeassistant-secure.service=homeassistant"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.docker.network=traefik_netZ"

       # Add CORS headers to Pi-hole container
      - "traefik.http.routers.homeassistant-secure.middlewares=homeassistant-cors"
      - "traefik.http.middlewares=homeassistant-cors"
      - "traefik.http.middlewares.homeassistant-cors.headers.accesscontrolalloworiginList=*"
      - "traefik.http.middlewares.homeassistant-cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.homeassistant-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.homeassistant-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.homeassistant-cors.headers.addvaryheader=true"

